### ISSUE TITLE
Context array details are overwritten by teardown data

### ISSUE THREAD

**Issue by sushilveer** [apoorvam/json-report#1]
teardown array object in JSON is always empty. Additionally, the context array is getting overwritten by the teardown array data. 

Steps to reproduce-

1. 

**Create a spec file as below-**
Specification Heading
=====================
Setup of contexts
* Context - setup

Scenario Heading
----------------
* Step1
* Step2
___

Teardown of contexts
* Context - teardown

2. 

**Create context and Fixture classes as below-**
In Fixture.java, we have
  @com.thoughtworks.gauge.Step("Step1")
  public void step1() throws Exception {
  }

  @com.thoughtworks.gauge.Step("Step2")
  public void step2() throws Exception {
  }

In Context.java, we can have
@com.thoughtworks.gauge.Step("Context - setup")
public void setUp() throws Exception {
}

@com.thoughtworks.gauge.Step("Context - teardown")
public void tearDown()throws Exception {
}

3. 

**Now try throwing an exception from context or teardown and observe** 

**Expected Results:**
_teardown failures should be rendered to the 'teardown' array of the JSON_ 

**Actual Result:**
- _teardown array of JSON is always blank_
- _context array is overwritten by teardown array data_

Gauge version: 0.8.1

Plugins
-------
html-report (3.1.0)
java (0.6.2.nightly-2017-03-22)
json-report (0.2.0)

**Comment by apoorvam** [comment]
@sushilveer Thanks for detailed issue notes. This should be fixed as part of new release of json-report v0.2.1. Please update plugin and try out!
