### ISSUE TITLE
There should be the total number of passed/failed/skipped scenario counts in the json-report

### ISSUE THREAD

**Issue by osandadeshan** [apoorvam/json-report#3]
### Expected behavior
The total number of passed/failed/skipped scenario counts should be inside the json-report

### Actual behavior
The total number of passed/failed/skipped scenario counts are not in the json-report

### Steps to reproduce
1. Run few spec files.
2. Go to the json-report
3. There are passed/failed/skipped scenario counts only for spec wise. There is no place to find the total number of passed/failed/skipped scenario counts.

**Note: For the Quality Engineers passed/failed/skipped scenario counts is a very important factor to measure the health of a give project. So it would be very much helpful if you can provide this feature..**

### Gauge version
```
Gauge version: 0.9.8
Commit Hash: c23df9f

Plugins
-------
csharp (0.10.3)
flash (0.0.1)
html-report (4.0.4)
java (0.6.7)
json-report (0.2.1)
ruby (0.5.0)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```

**Comment by apoorvam** [comment]
Fair enough. Will make this included and make a release.

**Comment by apoorvam** [comment]
@osandadeshan Try out latest release of json-report v0.2.2 with this enhancement included. 
Release: https://github.com/apoorvam/json-report/releases/tag/0.2.2

Let me know how it goes. For installation steps, refer: https://github.com/apoorvam/json-report#offline-installation
New release is yet to be updated in gauge though, try the offline installation.

**Comment by apoorvam** [comment]
This is fixed. Please use latest version of report. 

@osandadeshan
