### ISSUE TITLE
Gauge JSON report link in gauge plugins page points to wrong location

### ISSUE THREAD

**Issue by arun2sasi** [apoorvam/json-report#4]
In the below link , when I click on json plugin link, it takes me to xml report page insated of json page
https://gauge.org/plugins/#reports

**Comment by sriv** [comment]
thanks for reporting this. This is an issue with the gauge website and not specific to this plugin. I have pushed a commit with the correction.

**Comment by arun2sasi** [comment]
Thanks Sriv..I'll close the issue then..
