### ISSUE TITLE
Execution status should be in past tense

### ISSUE THREAD

**Issue by osandadeshan** [apoorvam/json-report#7]
**Steps to recreate:**

1. Run a sample project which has all the tests passed
2. Open json-report xml file
3. Execution status will be showing as "pass". It should be ""Passed"
4. Run a sample project which has all the tests failed
5. Open json-report xml file
6. Execution status will be showing as "fail". It should be "Failed"
7. Run a sample project which has all the tests skipped
8. Open json-report xml file
9. Execution status will be showing as "skip". It should be "Skipped"

**Gauge Version**
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins

flash (0.0.1)
html-report (4.0.6)
java (0.7.2.nightly-2019-03-07)
js (2.3.2)
json-report (0.2.2)
python (0.3.4)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)

**Comment by apoorvam** [comment]
@osandadeshan I think it sounds good if we change tense. Though it breaks backward compatibility for anyone doing string match.
Would you like to make a pull request with this change and test it? It should be simple with changes only in constants [here](https://github.com/apoorvam/json-report/blob/master/generate.go#L15). I can help with review and release.

**Comment by osandadeshan** [comment]
@apoorvam I have raised the PR for this. Please review.
https://github.com/apoorvam/json-report/pull/8

**Comment by apoorvam** [comment]
Done. 👍 Will make a release with the changes soon.

**Comment by osandadeshan** [comment]
Please let me know when this is available in a release (Not a nightly build)

**Comment by apoorvam** [comment]
@osandadeshan I have already made the release. But to be able to update via Gauge, a PR still needs to be merged by Gauge team. Will be done soon.

**Comment by rbelouin** [comment]
Hello! Would have been nice to bump a major version :)
Yep, I am that guy doing string match.
